version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "50051:50051"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
      - /usr/app/certs
    environment:
      - NODE_ENV=development